const overall={approved:82.1594,denied:17.8406};
const races=[["American Indian or Alaska Native",77.174],["Asian",83.254],["Black or African American",68.978],["Native Hawaiian or Other Pacific Islander",80.282],["White",83.470]];
const income={lower:{black:56.682,white:68.958},middle:{black:70.128,white:84.513},upper:{black:77.679,white:88.505}};
const root=document.getElementById("mortgageViz");
function bar(label,value,sub){return '<div class="m-row"><div class="m-label"><b>'+label+'</b><span>'+sub+'</span></div><div class="m-track"><i style="width:'+value+'%"></i></div><strong>'+value.toFixed(1)+'%</strong></div>'}
function render(v){
if(v==="overall")root.innerHTML='<div class="m-kpis"><div><span>APPROVED</span><b>82.2%</b></div><div><span>DENIED</span><b>17.8%</b></div><div><span>RECORDS</span><b>12,550</b></div></div><p class="m-caption">Overall approval and denial rates from the completed workbook.</p>';
if(v==="race"){root.innerHTML='<div class="m-control"><label>Display <select id="raceSort"><option value="approval">Approval rate</option><option value="denial">Denial rate</option></select></label></div><div id="raceBars"></div>';const draw=()=>{const denial=document.getElementById("raceSort").value==="denial";document.getElementById("raceBars").innerHTML=races.map(x=>bar(x[0],denial?100-x[1]:x[1],denial?"Denied":"Approved")).join("")};document.getElementById("raceSort").addEventListener("change",draw);draw()}
if(v==="income"){root.innerHTML='<div class="m-control"><label>Income category <select id="incomeSelect"><option value="lower">Lower · under $40k</option><option value="middle">Middle · $40k–$122k</option><option value="upper">Upper · over $122k</option></select></label></div><div id="incomeBars"></div><p id="gap" class="m-caption"></p>';const draw=()=>{const d=income[document.getElementById("incomeSelect").value],gap=d.white-d.black;document.getElementById("incomeBars").innerHTML=bar("Black or African American",d.black,"Approved")+bar("White",d.white,"Approved");document.getElementById("gap").textContent="Approval-rate difference: "+gap.toFixed(1)+" percentage points."};document.getElementById("incomeSelect").addEventListener("change",draw);draw()}
if(v==="test")root.innerHTML='<div class="m-test"><span>MIDDLE-INCOME TEST SUBSET</span><h3>African American and White Non-Hispanic applicants</h3><div class="m-teststats"><div><span>AFRICAN AMERICAN</span><b>69.6%</b><small>445 / 639 approved</small></div><div><span>WHITE NON-HISPANIC</span><b>85.0%</b><small>4,496 / 5,292 approved</small></div><div><span>DIFFERENCE</span><b>15.3 pp</b><small>approval rate</small></div><div><span>Z-STATISTIC</span><b>9.81</b><small>two-sided p &lt; 0.001</small></div></div><p class="m-caption">The observed difference is statistically significant in this sample. Statistical significance does not identify the cause of the difference.</p></div>';
}
document.querySelectorAll(".dash-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".dash-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.view)}));render("overall");